// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// CreateCubeSatFrameReader is a Reader for the CreateCubeSatFrame structure.
type CreateCubeSatFrameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCubeSatFrameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCubeSatFrameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCubeSatFrameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCubeSatFrameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateCubeSatFrameUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCubeSatFrameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cube_sat_frame] CreateCubeSatFrame", response, response.Code())
	}
}

// NewCreateCubeSatFrameOK creates a CreateCubeSatFrameOK with default headers values
func NewCreateCubeSatFrameOK() *CreateCubeSatFrameOK {
	return &CreateCubeSatFrameOK{}
}

/*
CreateCubeSatFrameOK describes a response with status code 200, with default header values.

Create Cube Sat Frame Response
*/
type CreateCubeSatFrameOK struct {
	Payload *models.CubeSatFrame
}

// IsSuccess returns true when this create cube sat frame o k response has a 2xx status code
func (o *CreateCubeSatFrameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create cube sat frame o k response has a 3xx status code
func (o *CreateCubeSatFrameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cube sat frame o k response has a 4xx status code
func (o *CreateCubeSatFrameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cube sat frame o k response has a 5xx status code
func (o *CreateCubeSatFrameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create cube sat frame o k response a status code equal to that given
func (o *CreateCubeSatFrameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create cube sat frame o k response
func (o *CreateCubeSatFrameOK) Code() int {
	return 200
}

func (o *CreateCubeSatFrameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameOK %s", 200, payload)
}

func (o *CreateCubeSatFrameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameOK %s", 200, payload)
}

func (o *CreateCubeSatFrameOK) GetPayload() *models.CubeSatFrame {
	return o.Payload
}

func (o *CreateCubeSatFrameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CubeSatFrame)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCubeSatFrameBadRequest creates a CreateCubeSatFrameBadRequest with default headers values
func NewCreateCubeSatFrameBadRequest() *CreateCubeSatFrameBadRequest {
	return &CreateCubeSatFrameBadRequest{}
}

/*
CreateCubeSatFrameBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateCubeSatFrameBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cube sat frame bad request response has a 2xx status code
func (o *CreateCubeSatFrameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cube sat frame bad request response has a 3xx status code
func (o *CreateCubeSatFrameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cube sat frame bad request response has a 4xx status code
func (o *CreateCubeSatFrameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cube sat frame bad request response has a 5xx status code
func (o *CreateCubeSatFrameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create cube sat frame bad request response a status code equal to that given
func (o *CreateCubeSatFrameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create cube sat frame bad request response
func (o *CreateCubeSatFrameBadRequest) Code() int {
	return 400
}

func (o *CreateCubeSatFrameBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameBadRequest %s", 400, payload)
}

func (o *CreateCubeSatFrameBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameBadRequest %s", 400, payload)
}

func (o *CreateCubeSatFrameBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCubeSatFrameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCubeSatFrameForbidden creates a CreateCubeSatFrameForbidden with default headers values
func NewCreateCubeSatFrameForbidden() *CreateCubeSatFrameForbidden {
	return &CreateCubeSatFrameForbidden{}
}

/*
CreateCubeSatFrameForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateCubeSatFrameForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cube sat frame forbidden response has a 2xx status code
func (o *CreateCubeSatFrameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cube sat frame forbidden response has a 3xx status code
func (o *CreateCubeSatFrameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cube sat frame forbidden response has a 4xx status code
func (o *CreateCubeSatFrameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cube sat frame forbidden response has a 5xx status code
func (o *CreateCubeSatFrameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create cube sat frame forbidden response a status code equal to that given
func (o *CreateCubeSatFrameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create cube sat frame forbidden response
func (o *CreateCubeSatFrameForbidden) Code() int {
	return 403
}

func (o *CreateCubeSatFrameForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameForbidden %s", 403, payload)
}

func (o *CreateCubeSatFrameForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameForbidden %s", 403, payload)
}

func (o *CreateCubeSatFrameForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCubeSatFrameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCubeSatFrameUnprocessableEntity creates a CreateCubeSatFrameUnprocessableEntity with default headers values
func NewCreateCubeSatFrameUnprocessableEntity() *CreateCubeSatFrameUnprocessableEntity {
	return &CreateCubeSatFrameUnprocessableEntity{}
}

/*
CreateCubeSatFrameUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type CreateCubeSatFrameUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cube sat frame unprocessable entity response has a 2xx status code
func (o *CreateCubeSatFrameUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cube sat frame unprocessable entity response has a 3xx status code
func (o *CreateCubeSatFrameUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cube sat frame unprocessable entity response has a 4xx status code
func (o *CreateCubeSatFrameUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cube sat frame unprocessable entity response has a 5xx status code
func (o *CreateCubeSatFrameUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create cube sat frame unprocessable entity response a status code equal to that given
func (o *CreateCubeSatFrameUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create cube sat frame unprocessable entity response
func (o *CreateCubeSatFrameUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateCubeSatFrameUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameUnprocessableEntity %s", 422, payload)
}

func (o *CreateCubeSatFrameUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameUnprocessableEntity %s", 422, payload)
}

func (o *CreateCubeSatFrameUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCubeSatFrameUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCubeSatFrameInternalServerError creates a CreateCubeSatFrameInternalServerError with default headers values
func NewCreateCubeSatFrameInternalServerError() *CreateCubeSatFrameInternalServerError {
	return &CreateCubeSatFrameInternalServerError{}
}

/*
CreateCubeSatFrameInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type CreateCubeSatFrameInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cube sat frame internal server error response has a 2xx status code
func (o *CreateCubeSatFrameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cube sat frame internal server error response has a 3xx status code
func (o *CreateCubeSatFrameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cube sat frame internal server error response has a 4xx status code
func (o *CreateCubeSatFrameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cube sat frame internal server error response has a 5xx status code
func (o *CreateCubeSatFrameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create cube sat frame internal server error response a status code equal to that given
func (o *CreateCubeSatFrameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create cube sat frame internal server error response
func (o *CreateCubeSatFrameInternalServerError) Code() int {
	return 500
}

func (o *CreateCubeSatFrameInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameInternalServerError %s", 500, payload)
}

func (o *CreateCubeSatFrameInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cube_sat_frame][%d] createCubeSatFrameInternalServerError %s", 500, payload)
}

func (o *CreateCubeSatFrameInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCubeSatFrameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
