// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// NewCreateBoardComputingModuleParams creates a new CreateBoardComputingModuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBoardComputingModuleParams() *CreateBoardComputingModuleParams {
	return &CreateBoardComputingModuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBoardComputingModuleParamsWithTimeout creates a new CreateBoardComputingModuleParams object
// with the ability to set a timeout on a request.
func NewCreateBoardComputingModuleParamsWithTimeout(timeout time.Duration) *CreateBoardComputingModuleParams {
	return &CreateBoardComputingModuleParams{
		timeout: timeout,
	}
}

// NewCreateBoardComputingModuleParamsWithContext creates a new CreateBoardComputingModuleParams object
// with the ability to set a context for a request.
func NewCreateBoardComputingModuleParamsWithContext(ctx context.Context) *CreateBoardComputingModuleParams {
	return &CreateBoardComputingModuleParams{
		Context: ctx,
	}
}

// NewCreateBoardComputingModuleParamsWithHTTPClient creates a new CreateBoardComputingModuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBoardComputingModuleParamsWithHTTPClient(client *http.Client) *CreateBoardComputingModuleParams {
	return &CreateBoardComputingModuleParams{
		HTTPClient: client,
	}
}

/*
CreateBoardComputingModuleParams contains all the parameters to send to the API endpoint

	for the create board computing module operation.

	Typically these are written to a http.Request.
*/
type CreateBoardComputingModuleParams struct {

	/* BoardComputingModule.

	   Board Computing Module object to be created
	*/
	BoardComputingModule *models.CreateBoardComputingModuleBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create board computing module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBoardComputingModuleParams) WithDefaults() *CreateBoardComputingModuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create board computing module params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBoardComputingModuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create board computing module params
func (o *CreateBoardComputingModuleParams) WithTimeout(timeout time.Duration) *CreateBoardComputingModuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create board computing module params
func (o *CreateBoardComputingModuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create board computing module params
func (o *CreateBoardComputingModuleParams) WithContext(ctx context.Context) *CreateBoardComputingModuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create board computing module params
func (o *CreateBoardComputingModuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create board computing module params
func (o *CreateBoardComputingModuleParams) WithHTTPClient(client *http.Client) *CreateBoardComputingModuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create board computing module params
func (o *CreateBoardComputingModuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBoardComputingModule adds the boardComputingModule to the create board computing module params
func (o *CreateBoardComputingModuleParams) WithBoardComputingModule(boardComputingModule *models.CreateBoardComputingModuleBody) *CreateBoardComputingModuleParams {
	o.SetBoardComputingModule(boardComputingModule)
	return o
}

// SetBoardComputingModule adds the boardComputingModule to the create board computing module params
func (o *CreateBoardComputingModuleParams) SetBoardComputingModule(boardComputingModule *models.CreateBoardComputingModuleBody) {
	o.BoardComputingModule = boardComputingModule
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBoardComputingModuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.BoardComputingModule != nil {
		if err := r.SetBodyParam(o.BoardComputingModule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
