// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCubeSatPowerSystemParams creates a new DeleteCubeSatPowerSystemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCubeSatPowerSystemParams() *DeleteCubeSatPowerSystemParams {
	return &DeleteCubeSatPowerSystemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCubeSatPowerSystemParamsWithTimeout creates a new DeleteCubeSatPowerSystemParams object
// with the ability to set a timeout on a request.
func NewDeleteCubeSatPowerSystemParamsWithTimeout(timeout time.Duration) *DeleteCubeSatPowerSystemParams {
	return &DeleteCubeSatPowerSystemParams{
		timeout: timeout,
	}
}

// NewDeleteCubeSatPowerSystemParamsWithContext creates a new DeleteCubeSatPowerSystemParams object
// with the ability to set a context for a request.
func NewDeleteCubeSatPowerSystemParamsWithContext(ctx context.Context) *DeleteCubeSatPowerSystemParams {
	return &DeleteCubeSatPowerSystemParams{
		Context: ctx,
	}
}

// NewDeleteCubeSatPowerSystemParamsWithHTTPClient creates a new DeleteCubeSatPowerSystemParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCubeSatPowerSystemParamsWithHTTPClient(client *http.Client) *DeleteCubeSatPowerSystemParams {
	return &DeleteCubeSatPowerSystemParams{
		HTTPClient: client,
	}
}

/*
DeleteCubeSatPowerSystemParams contains all the parameters to send to the API endpoint

	for the delete cube sat power system operation.

	Typically these are written to a http.Request.
*/
type DeleteCubeSatPowerSystemParams struct {

	/* ID.

	   The ID of the cube sat power system
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cube sat power system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCubeSatPowerSystemParams) WithDefaults() *DeleteCubeSatPowerSystemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cube sat power system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCubeSatPowerSystemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) WithTimeout(timeout time.Duration) *DeleteCubeSatPowerSystemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) WithContext(ctx context.Context) *DeleteCubeSatPowerSystemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) WithHTTPClient(client *http.Client) *DeleteCubeSatPowerSystemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) WithID(id int64) *DeleteCubeSatPowerSystemParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete cube sat power system params
func (o *DeleteCubeSatPowerSystemParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCubeSatPowerSystemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
