// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteChassisParams creates a new DeleteChassisParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteChassisParams() *DeleteChassisParams {
	return &DeleteChassisParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteChassisParamsWithTimeout creates a new DeleteChassisParams object
// with the ability to set a timeout on a request.
func NewDeleteChassisParamsWithTimeout(timeout time.Duration) *DeleteChassisParams {
	return &DeleteChassisParams{
		timeout: timeout,
	}
}

// NewDeleteChassisParamsWithContext creates a new DeleteChassisParams object
// with the ability to set a context for a request.
func NewDeleteChassisParamsWithContext(ctx context.Context) *DeleteChassisParams {
	return &DeleteChassisParams{
		Context: ctx,
	}
}

// NewDeleteChassisParamsWithHTTPClient creates a new DeleteChassisParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteChassisParamsWithHTTPClient(client *http.Client) *DeleteChassisParams {
	return &DeleteChassisParams{
		HTTPClient: client,
	}
}

/*
DeleteChassisParams contains all the parameters to send to the API endpoint

	for the delete chassis operation.

	Typically these are written to a http.Request.
*/
type DeleteChassisParams struct {

	/* ID.

	   The ID of the chassis
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete chassis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteChassisParams) WithDefaults() *DeleteChassisParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete chassis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteChassisParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete chassis params
func (o *DeleteChassisParams) WithTimeout(timeout time.Duration) *DeleteChassisParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete chassis params
func (o *DeleteChassisParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete chassis params
func (o *DeleteChassisParams) WithContext(ctx context.Context) *DeleteChassisParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete chassis params
func (o *DeleteChassisParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete chassis params
func (o *DeleteChassisParams) WithHTTPClient(client *http.Client) *DeleteChassisParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete chassis params
func (o *DeleteChassisParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete chassis params
func (o *DeleteChassisParams) WithID(id int64) *DeleteChassisParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete chassis params
func (o *DeleteChassisParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteChassisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
