// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// DeleteVHFAntennaSystemReader is a Reader for the DeleteVHFAntennaSystem structure.
type DeleteVHFAntennaSystemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteVHFAntennaSystemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteVHFAntennaSystemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteVHFAntennaSystemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteVHFAntennaSystemForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteVHFAntennaSystemUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteVHFAntennaSystemInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /vhf_antenna_system/{id}] DeleteVHFAntennaSystem", response, response.Code())
	}
}

// NewDeleteVHFAntennaSystemOK creates a DeleteVHFAntennaSystemOK with default headers values
func NewDeleteVHFAntennaSystemOK() *DeleteVHFAntennaSystemOK {
	return &DeleteVHFAntennaSystemOK{}
}

/*
DeleteVHFAntennaSystemOK describes a response with status code 200, with default header values.

Delete VHF Antenna System Response
*/
type DeleteVHFAntennaSystemOK struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete v h f antenna system o k response has a 2xx status code
func (o *DeleteVHFAntennaSystemOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v h f antenna system o k response has a 3xx status code
func (o *DeleteVHFAntennaSystemOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v h f antenna system o k response has a 4xx status code
func (o *DeleteVHFAntennaSystemOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v h f antenna system o k response has a 5xx status code
func (o *DeleteVHFAntennaSystemOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v h f antenna system o k response a status code equal to that given
func (o *DeleteVHFAntennaSystemOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete v h f antenna system o k response
func (o *DeleteVHFAntennaSystemOK) Code() int {
	return 200
}

func (o *DeleteVHFAntennaSystemOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemOK %s", 200, payload)
}

func (o *DeleteVHFAntennaSystemOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemOK %s", 200, payload)
}

func (o *DeleteVHFAntennaSystemOK) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVHFAntennaSystemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteVHFAntennaSystemBadRequest creates a DeleteVHFAntennaSystemBadRequest with default headers values
func NewDeleteVHFAntennaSystemBadRequest() *DeleteVHFAntennaSystemBadRequest {
	return &DeleteVHFAntennaSystemBadRequest{}
}

/*
DeleteVHFAntennaSystemBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteVHFAntennaSystemBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete v h f antenna system bad request response has a 2xx status code
func (o *DeleteVHFAntennaSystemBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v h f antenna system bad request response has a 3xx status code
func (o *DeleteVHFAntennaSystemBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v h f antenna system bad request response has a 4xx status code
func (o *DeleteVHFAntennaSystemBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v h f antenna system bad request response has a 5xx status code
func (o *DeleteVHFAntennaSystemBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v h f antenna system bad request response a status code equal to that given
func (o *DeleteVHFAntennaSystemBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete v h f antenna system bad request response
func (o *DeleteVHFAntennaSystemBadRequest) Code() int {
	return 400
}

func (o *DeleteVHFAntennaSystemBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemBadRequest %s", 400, payload)
}

func (o *DeleteVHFAntennaSystemBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemBadRequest %s", 400, payload)
}

func (o *DeleteVHFAntennaSystemBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVHFAntennaSystemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteVHFAntennaSystemForbidden creates a DeleteVHFAntennaSystemForbidden with default headers values
func NewDeleteVHFAntennaSystemForbidden() *DeleteVHFAntennaSystemForbidden {
	return &DeleteVHFAntennaSystemForbidden{}
}

/*
DeleteVHFAntennaSystemForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteVHFAntennaSystemForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete v h f antenna system forbidden response has a 2xx status code
func (o *DeleteVHFAntennaSystemForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v h f antenna system forbidden response has a 3xx status code
func (o *DeleteVHFAntennaSystemForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v h f antenna system forbidden response has a 4xx status code
func (o *DeleteVHFAntennaSystemForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v h f antenna system forbidden response has a 5xx status code
func (o *DeleteVHFAntennaSystemForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v h f antenna system forbidden response a status code equal to that given
func (o *DeleteVHFAntennaSystemForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete v h f antenna system forbidden response
func (o *DeleteVHFAntennaSystemForbidden) Code() int {
	return 403
}

func (o *DeleteVHFAntennaSystemForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemForbidden %s", 403, payload)
}

func (o *DeleteVHFAntennaSystemForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemForbidden %s", 403, payload)
}

func (o *DeleteVHFAntennaSystemForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVHFAntennaSystemForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteVHFAntennaSystemUnprocessableEntity creates a DeleteVHFAntennaSystemUnprocessableEntity with default headers values
func NewDeleteVHFAntennaSystemUnprocessableEntity() *DeleteVHFAntennaSystemUnprocessableEntity {
	return &DeleteVHFAntennaSystemUnprocessableEntity{}
}

/*
DeleteVHFAntennaSystemUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type DeleteVHFAntennaSystemUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete v h f antenna system unprocessable entity response has a 2xx status code
func (o *DeleteVHFAntennaSystemUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v h f antenna system unprocessable entity response has a 3xx status code
func (o *DeleteVHFAntennaSystemUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v h f antenna system unprocessable entity response has a 4xx status code
func (o *DeleteVHFAntennaSystemUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete v h f antenna system unprocessable entity response has a 5xx status code
func (o *DeleteVHFAntennaSystemUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v h f antenna system unprocessable entity response a status code equal to that given
func (o *DeleteVHFAntennaSystemUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the delete v h f antenna system unprocessable entity response
func (o *DeleteVHFAntennaSystemUnprocessableEntity) Code() int {
	return 422
}

func (o *DeleteVHFAntennaSystemUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemUnprocessableEntity %s", 422, payload)
}

func (o *DeleteVHFAntennaSystemUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemUnprocessableEntity %s", 422, payload)
}

func (o *DeleteVHFAntennaSystemUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVHFAntennaSystemUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteVHFAntennaSystemInternalServerError creates a DeleteVHFAntennaSystemInternalServerError with default headers values
func NewDeleteVHFAntennaSystemInternalServerError() *DeleteVHFAntennaSystemInternalServerError {
	return &DeleteVHFAntennaSystemInternalServerError{}
}

/*
DeleteVHFAntennaSystemInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteVHFAntennaSystemInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete v h f antenna system internal server error response has a 2xx status code
func (o *DeleteVHFAntennaSystemInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete v h f antenna system internal server error response has a 3xx status code
func (o *DeleteVHFAntennaSystemInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v h f antenna system internal server error response has a 4xx status code
func (o *DeleteVHFAntennaSystemInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v h f antenna system internal server error response has a 5xx status code
func (o *DeleteVHFAntennaSystemInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete v h f antenna system internal server error response a status code equal to that given
func (o *DeleteVHFAntennaSystemInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete v h f antenna system internal server error response
func (o *DeleteVHFAntennaSystemInternalServerError) Code() int {
	return 500
}

func (o *DeleteVHFAntennaSystemInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemInternalServerError %s", 500, payload)
}

func (o *DeleteVHFAntennaSystemInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /vhf_antenna_system/{id}][%d] deleteVHFAntennaSystemInternalServerError %s", 500, payload)
}

func (o *DeleteVHFAntennaSystemInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteVHFAntennaSystemInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
