// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCubeSatVHFTransceiverParams creates a new DeleteCubeSatVHFTransceiverParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCubeSatVHFTransceiverParams() *DeleteCubeSatVHFTransceiverParams {
	return &DeleteCubeSatVHFTransceiverParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCubeSatVHFTransceiverParamsWithTimeout creates a new DeleteCubeSatVHFTransceiverParams object
// with the ability to set a timeout on a request.
func NewDeleteCubeSatVHFTransceiverParamsWithTimeout(timeout time.Duration) *DeleteCubeSatVHFTransceiverParams {
	return &DeleteCubeSatVHFTransceiverParams{
		timeout: timeout,
	}
}

// NewDeleteCubeSatVHFTransceiverParamsWithContext creates a new DeleteCubeSatVHFTransceiverParams object
// with the ability to set a context for a request.
func NewDeleteCubeSatVHFTransceiverParamsWithContext(ctx context.Context) *DeleteCubeSatVHFTransceiverParams {
	return &DeleteCubeSatVHFTransceiverParams{
		Context: ctx,
	}
}

// NewDeleteCubeSatVHFTransceiverParamsWithHTTPClient creates a new DeleteCubeSatVHFTransceiverParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCubeSatVHFTransceiverParamsWithHTTPClient(client *http.Client) *DeleteCubeSatVHFTransceiverParams {
	return &DeleteCubeSatVHFTransceiverParams{
		HTTPClient: client,
	}
}

/*
DeleteCubeSatVHFTransceiverParams contains all the parameters to send to the API endpoint

	for the delete cube sat v h f transceiver operation.

	Typically these are written to a http.Request.
*/
type DeleteCubeSatVHFTransceiverParams struct {

	/* ID.

	   The ID of the CubeSat VHF transceiver
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cube sat v h f transceiver params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCubeSatVHFTransceiverParams) WithDefaults() *DeleteCubeSatVHFTransceiverParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cube sat v h f transceiver params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCubeSatVHFTransceiverParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) WithTimeout(timeout time.Duration) *DeleteCubeSatVHFTransceiverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) WithContext(ctx context.Context) *DeleteCubeSatVHFTransceiverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) WithHTTPClient(client *http.Client) *DeleteCubeSatVHFTransceiverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) WithID(id int64) *DeleteCubeSatVHFTransceiverParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete cube sat v h f transceiver params
func (o *DeleteCubeSatVHFTransceiverParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCubeSatVHFTransceiverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
