// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// GetAvailableCubeSatVHTransceiversReader is a Reader for the GetAvailableCubeSatVHTransceivers structure.
type GetAvailableCubeSatVHTransceiversReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAvailableCubeSatVHTransceiversReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAvailableCubeSatVHTransceiversOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAvailableCubeSatVHTransceiversBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAvailableCubeSatVHTransceiversForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetAvailableCubeSatVHTransceiversUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAvailableCubeSatVHTransceiversInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cube_sat_vhf_transceiver/available] GetAvailableCubeSatVHTransceivers", response, response.Code())
	}
}

// NewGetAvailableCubeSatVHTransceiversOK creates a GetAvailableCubeSatVHTransceiversOK with default headers values
func NewGetAvailableCubeSatVHTransceiversOK() *GetAvailableCubeSatVHTransceiversOK {
	return &GetAvailableCubeSatVHTransceiversOK{}
}

/*
GetAvailableCubeSatVHTransceiversOK describes a response with status code 200, with default header values.

Get Available CubeSat VHF Transceivers Response
*/
type GetAvailableCubeSatVHTransceiversOK struct {
	Payload *models.CubeSatVHFTransceivers
}

// IsSuccess returns true when this get available cube sat v h transceivers o k response has a 2xx status code
func (o *GetAvailableCubeSatVHTransceiversOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get available cube sat v h transceivers o k response has a 3xx status code
func (o *GetAvailableCubeSatVHTransceiversOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available cube sat v h transceivers o k response has a 4xx status code
func (o *GetAvailableCubeSatVHTransceiversOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get available cube sat v h transceivers o k response has a 5xx status code
func (o *GetAvailableCubeSatVHTransceiversOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get available cube sat v h transceivers o k response a status code equal to that given
func (o *GetAvailableCubeSatVHTransceiversOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get available cube sat v h transceivers o k response
func (o *GetAvailableCubeSatVHTransceiversOK) Code() int {
	return 200
}

func (o *GetAvailableCubeSatVHTransceiversOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversOK %s", 200, payload)
}

func (o *GetAvailableCubeSatVHTransceiversOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversOK %s", 200, payload)
}

func (o *GetAvailableCubeSatVHTransceiversOK) GetPayload() *models.CubeSatVHFTransceivers {
	return o.Payload
}

func (o *GetAvailableCubeSatVHTransceiversOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CubeSatVHFTransceivers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAvailableCubeSatVHTransceiversBadRequest creates a GetAvailableCubeSatVHTransceiversBadRequest with default headers values
func NewGetAvailableCubeSatVHTransceiversBadRequest() *GetAvailableCubeSatVHTransceiversBadRequest {
	return &GetAvailableCubeSatVHTransceiversBadRequest{}
}

/*
GetAvailableCubeSatVHTransceiversBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetAvailableCubeSatVHTransceiversBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get available cube sat v h transceivers bad request response has a 2xx status code
func (o *GetAvailableCubeSatVHTransceiversBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available cube sat v h transceivers bad request response has a 3xx status code
func (o *GetAvailableCubeSatVHTransceiversBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available cube sat v h transceivers bad request response has a 4xx status code
func (o *GetAvailableCubeSatVHTransceiversBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available cube sat v h transceivers bad request response has a 5xx status code
func (o *GetAvailableCubeSatVHTransceiversBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get available cube sat v h transceivers bad request response a status code equal to that given
func (o *GetAvailableCubeSatVHTransceiversBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get available cube sat v h transceivers bad request response
func (o *GetAvailableCubeSatVHTransceiversBadRequest) Code() int {
	return 400
}

func (o *GetAvailableCubeSatVHTransceiversBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversBadRequest %s", 400, payload)
}

func (o *GetAvailableCubeSatVHTransceiversBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversBadRequest %s", 400, payload)
}

func (o *GetAvailableCubeSatVHTransceiversBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAvailableCubeSatVHTransceiversBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAvailableCubeSatVHTransceiversForbidden creates a GetAvailableCubeSatVHTransceiversForbidden with default headers values
func NewGetAvailableCubeSatVHTransceiversForbidden() *GetAvailableCubeSatVHTransceiversForbidden {
	return &GetAvailableCubeSatVHTransceiversForbidden{}
}

/*
GetAvailableCubeSatVHTransceiversForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAvailableCubeSatVHTransceiversForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this get available cube sat v h transceivers forbidden response has a 2xx status code
func (o *GetAvailableCubeSatVHTransceiversForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available cube sat v h transceivers forbidden response has a 3xx status code
func (o *GetAvailableCubeSatVHTransceiversForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available cube sat v h transceivers forbidden response has a 4xx status code
func (o *GetAvailableCubeSatVHTransceiversForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available cube sat v h transceivers forbidden response has a 5xx status code
func (o *GetAvailableCubeSatVHTransceiversForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get available cube sat v h transceivers forbidden response a status code equal to that given
func (o *GetAvailableCubeSatVHTransceiversForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get available cube sat v h transceivers forbidden response
func (o *GetAvailableCubeSatVHTransceiversForbidden) Code() int {
	return 403
}

func (o *GetAvailableCubeSatVHTransceiversForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversForbidden %s", 403, payload)
}

func (o *GetAvailableCubeSatVHTransceiversForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversForbidden %s", 403, payload)
}

func (o *GetAvailableCubeSatVHTransceiversForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAvailableCubeSatVHTransceiversForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAvailableCubeSatVHTransceiversUnprocessableEntity creates a GetAvailableCubeSatVHTransceiversUnprocessableEntity with default headers values
func NewGetAvailableCubeSatVHTransceiversUnprocessableEntity() *GetAvailableCubeSatVHTransceiversUnprocessableEntity {
	return &GetAvailableCubeSatVHTransceiversUnprocessableEntity{}
}

/*
GetAvailableCubeSatVHTransceiversUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type GetAvailableCubeSatVHTransceiversUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this get available cube sat v h transceivers unprocessable entity response has a 2xx status code
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available cube sat v h transceivers unprocessable entity response has a 3xx status code
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available cube sat v h transceivers unprocessable entity response has a 4xx status code
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available cube sat v h transceivers unprocessable entity response has a 5xx status code
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get available cube sat v h transceivers unprocessable entity response a status code equal to that given
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get available cube sat v h transceivers unprocessable entity response
func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) Code() int {
	return 422
}

func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversUnprocessableEntity %s", 422, payload)
}

func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversUnprocessableEntity %s", 422, payload)
}

func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAvailableCubeSatVHTransceiversUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAvailableCubeSatVHTransceiversInternalServerError creates a GetAvailableCubeSatVHTransceiversInternalServerError with default headers values
func NewGetAvailableCubeSatVHTransceiversInternalServerError() *GetAvailableCubeSatVHTransceiversInternalServerError {
	return &GetAvailableCubeSatVHTransceiversInternalServerError{}
}

/*
GetAvailableCubeSatVHTransceiversInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAvailableCubeSatVHTransceiversInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get available cube sat v h transceivers internal server error response has a 2xx status code
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available cube sat v h transceivers internal server error response has a 3xx status code
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available cube sat v h transceivers internal server error response has a 4xx status code
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get available cube sat v h transceivers internal server error response has a 5xx status code
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get available cube sat v h transceivers internal server error response a status code equal to that given
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get available cube sat v h transceivers internal server error response
func (o *GetAvailableCubeSatVHTransceiversInternalServerError) Code() int {
	return 500
}

func (o *GetAvailableCubeSatVHTransceiversInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversInternalServerError %s", 500, payload)
}

func (o *GetAvailableCubeSatVHTransceiversInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/available][%d] getAvailableCubeSatVHTransceiversInternalServerError %s", 500, payload)
}

func (o *GetAvailableCubeSatVHTransceiversInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAvailableCubeSatVHTransceiversInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
