// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserCubeSatProjectsParams creates a new GetUserCubeSatProjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserCubeSatProjectsParams() *GetUserCubeSatProjectsParams {
	return &GetUserCubeSatProjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserCubeSatProjectsParamsWithTimeout creates a new GetUserCubeSatProjectsParams object
// with the ability to set a timeout on a request.
func NewGetUserCubeSatProjectsParamsWithTimeout(timeout time.Duration) *GetUserCubeSatProjectsParams {
	return &GetUserCubeSatProjectsParams{
		timeout: timeout,
	}
}

// NewGetUserCubeSatProjectsParamsWithContext creates a new GetUserCubeSatProjectsParams object
// with the ability to set a context for a request.
func NewGetUserCubeSatProjectsParamsWithContext(ctx context.Context) *GetUserCubeSatProjectsParams {
	return &GetUserCubeSatProjectsParams{
		Context: ctx,
	}
}

// NewGetUserCubeSatProjectsParamsWithHTTPClient creates a new GetUserCubeSatProjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserCubeSatProjectsParamsWithHTTPClient(client *http.Client) *GetUserCubeSatProjectsParams {
	return &GetUserCubeSatProjectsParams{
		HTTPClient: client,
	}
}

/*
GetUserCubeSatProjectsParams contains all the parameters to send to the API endpoint

	for the get user cube sat projects operation.

	Typically these are written to a http.Request.
*/
type GetUserCubeSatProjectsParams struct {

	/* Limit.

	   Offset Configs
	*/
	Limit int64

	/* Offset.

	   Offset Configs
	*/
	Offset int64

	/* SortField.

	   sort parametrs
	*/
	SortField *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user cube sat projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserCubeSatProjectsParams) WithDefaults() *GetUserCubeSatProjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user cube sat projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserCubeSatProjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithTimeout(timeout time.Duration) *GetUserCubeSatProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithContext(ctx context.Context) *GetUserCubeSatProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithHTTPClient(client *http.Client) *GetUserCubeSatProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithLimit(limit int64) *GetUserCubeSatProjectsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithOffset(offset int64) *GetUserCubeSatProjectsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WithSortField adds the sortField to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) WithSortField(sortField *string) *GetUserCubeSatProjectsParams {
	o.SetSortField(sortField)
	return o
}

// SetSortField adds the sortField to the get user cube sat projects params
func (o *GetUserCubeSatProjectsParams) SetSortField(sortField *string) {
	o.SortField = sortField
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserCubeSatProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {

		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {

		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if o.SortField != nil {

		// query param sort[field]
		var qrSortField string

		if o.SortField != nil {
			qrSortField = *o.SortField
		}
		qSortField := qrSortField
		if qSortField != "" {

			if err := r.SetQueryParam("sort[field]", qSortField); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
