// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// GetCubeSatVHFTransceiverReader is a Reader for the GetCubeSatVHFTransceiver structure.
type GetCubeSatVHFTransceiverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCubeSatVHFTransceiverReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCubeSatVHFTransceiverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCubeSatVHFTransceiverBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCubeSatVHFTransceiverForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetCubeSatVHFTransceiverUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCubeSatVHFTransceiverInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cube_sat_vhf_transceiver/{id}] GetCubeSatVHFTransceiver", response, response.Code())
	}
}

// NewGetCubeSatVHFTransceiverOK creates a GetCubeSatVHFTransceiverOK with default headers values
func NewGetCubeSatVHFTransceiverOK() *GetCubeSatVHFTransceiverOK {
	return &GetCubeSatVHFTransceiverOK{}
}

/*
GetCubeSatVHFTransceiverOK describes a response with status code 200, with default header values.

Get CubeSat VHF Transceiver Response
*/
type GetCubeSatVHFTransceiverOK struct {
	Payload *models.VHFTransceiver
}

// IsSuccess returns true when this get cube sat v h f transceiver o k response has a 2xx status code
func (o *GetCubeSatVHFTransceiverOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cube sat v h f transceiver o k response has a 3xx status code
func (o *GetCubeSatVHFTransceiverOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cube sat v h f transceiver o k response has a 4xx status code
func (o *GetCubeSatVHFTransceiverOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cube sat v h f transceiver o k response has a 5xx status code
func (o *GetCubeSatVHFTransceiverOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cube sat v h f transceiver o k response a status code equal to that given
func (o *GetCubeSatVHFTransceiverOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cube sat v h f transceiver o k response
func (o *GetCubeSatVHFTransceiverOK) Code() int {
	return 200
}

func (o *GetCubeSatVHFTransceiverOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverOK %s", 200, payload)
}

func (o *GetCubeSatVHFTransceiverOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverOK %s", 200, payload)
}

func (o *GetCubeSatVHFTransceiverOK) GetPayload() *models.VHFTransceiver {
	return o.Payload
}

func (o *GetCubeSatVHFTransceiverOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VHFTransceiver)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCubeSatVHFTransceiverBadRequest creates a GetCubeSatVHFTransceiverBadRequest with default headers values
func NewGetCubeSatVHFTransceiverBadRequest() *GetCubeSatVHFTransceiverBadRequest {
	return &GetCubeSatVHFTransceiverBadRequest{}
}

/*
GetCubeSatVHFTransceiverBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetCubeSatVHFTransceiverBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cube sat v h f transceiver bad request response has a 2xx status code
func (o *GetCubeSatVHFTransceiverBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cube sat v h f transceiver bad request response has a 3xx status code
func (o *GetCubeSatVHFTransceiverBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cube sat v h f transceiver bad request response has a 4xx status code
func (o *GetCubeSatVHFTransceiverBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cube sat v h f transceiver bad request response has a 5xx status code
func (o *GetCubeSatVHFTransceiverBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get cube sat v h f transceiver bad request response a status code equal to that given
func (o *GetCubeSatVHFTransceiverBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get cube sat v h f transceiver bad request response
func (o *GetCubeSatVHFTransceiverBadRequest) Code() int {
	return 400
}

func (o *GetCubeSatVHFTransceiverBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverBadRequest %s", 400, payload)
}

func (o *GetCubeSatVHFTransceiverBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverBadRequest %s", 400, payload)
}

func (o *GetCubeSatVHFTransceiverBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCubeSatVHFTransceiverBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCubeSatVHFTransceiverForbidden creates a GetCubeSatVHFTransceiverForbidden with default headers values
func NewGetCubeSatVHFTransceiverForbidden() *GetCubeSatVHFTransceiverForbidden {
	return &GetCubeSatVHFTransceiverForbidden{}
}

/*
GetCubeSatVHFTransceiverForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetCubeSatVHFTransceiverForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cube sat v h f transceiver forbidden response has a 2xx status code
func (o *GetCubeSatVHFTransceiverForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cube sat v h f transceiver forbidden response has a 3xx status code
func (o *GetCubeSatVHFTransceiverForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cube sat v h f transceiver forbidden response has a 4xx status code
func (o *GetCubeSatVHFTransceiverForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cube sat v h f transceiver forbidden response has a 5xx status code
func (o *GetCubeSatVHFTransceiverForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get cube sat v h f transceiver forbidden response a status code equal to that given
func (o *GetCubeSatVHFTransceiverForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get cube sat v h f transceiver forbidden response
func (o *GetCubeSatVHFTransceiverForbidden) Code() int {
	return 403
}

func (o *GetCubeSatVHFTransceiverForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverForbidden %s", 403, payload)
}

func (o *GetCubeSatVHFTransceiverForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverForbidden %s", 403, payload)
}

func (o *GetCubeSatVHFTransceiverForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCubeSatVHFTransceiverForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCubeSatVHFTransceiverUnprocessableEntity creates a GetCubeSatVHFTransceiverUnprocessableEntity with default headers values
func NewGetCubeSatVHFTransceiverUnprocessableEntity() *GetCubeSatVHFTransceiverUnprocessableEntity {
	return &GetCubeSatVHFTransceiverUnprocessableEntity{}
}

/*
GetCubeSatVHFTransceiverUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type GetCubeSatVHFTransceiverUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cube sat v h f transceiver unprocessable entity response has a 2xx status code
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cube sat v h f transceiver unprocessable entity response has a 3xx status code
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cube sat v h f transceiver unprocessable entity response has a 4xx status code
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cube sat v h f transceiver unprocessable entity response has a 5xx status code
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get cube sat v h f transceiver unprocessable entity response a status code equal to that given
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get cube sat v h f transceiver unprocessable entity response
func (o *GetCubeSatVHFTransceiverUnprocessableEntity) Code() int {
	return 422
}

func (o *GetCubeSatVHFTransceiverUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverUnprocessableEntity %s", 422, payload)
}

func (o *GetCubeSatVHFTransceiverUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverUnprocessableEntity %s", 422, payload)
}

func (o *GetCubeSatVHFTransceiverUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCubeSatVHFTransceiverUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCubeSatVHFTransceiverInternalServerError creates a GetCubeSatVHFTransceiverInternalServerError with default headers values
func NewGetCubeSatVHFTransceiverInternalServerError() *GetCubeSatVHFTransceiverInternalServerError {
	return &GetCubeSatVHFTransceiverInternalServerError{}
}

/*
GetCubeSatVHFTransceiverInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetCubeSatVHFTransceiverInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cube sat v h f transceiver internal server error response has a 2xx status code
func (o *GetCubeSatVHFTransceiverInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cube sat v h f transceiver internal server error response has a 3xx status code
func (o *GetCubeSatVHFTransceiverInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cube sat v h f transceiver internal server error response has a 4xx status code
func (o *GetCubeSatVHFTransceiverInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cube sat v h f transceiver internal server error response has a 5xx status code
func (o *GetCubeSatVHFTransceiverInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get cube sat v h f transceiver internal server error response a status code equal to that given
func (o *GetCubeSatVHFTransceiverInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get cube sat v h f transceiver internal server error response
func (o *GetCubeSatVHFTransceiverInternalServerError) Code() int {
	return 500
}

func (o *GetCubeSatVHFTransceiverInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverInternalServerError %s", 500, payload)
}

func (o *GetCubeSatVHFTransceiverInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cube_sat_vhf_transceiver/{id}][%d] getCubeSatVHFTransceiverInternalServerError %s", 500, payload)
}

func (o *GetCubeSatVHFTransceiverInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCubeSatVHFTransceiverInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
