// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAvailableCubeSatVHFTransceiversParams creates a new GetAvailableCubeSatVHFTransceiversParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAvailableCubeSatVHFTransceiversParams() *GetAvailableCubeSatVHFTransceiversParams {
	return &GetAvailableCubeSatVHFTransceiversParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAvailableCubeSatVHFTransceiversParamsWithTimeout creates a new GetAvailableCubeSatVHFTransceiversParams object
// with the ability to set a timeout on a request.
func NewGetAvailableCubeSatVHFTransceiversParamsWithTimeout(timeout time.Duration) *GetAvailableCubeSatVHFTransceiversParams {
	return &GetAvailableCubeSatVHFTransceiversParams{
		timeout: timeout,
	}
}

// NewGetAvailableCubeSatVHFTransceiversParamsWithContext creates a new GetAvailableCubeSatVHFTransceiversParams object
// with the ability to set a context for a request.
func NewGetAvailableCubeSatVHFTransceiversParamsWithContext(ctx context.Context) *GetAvailableCubeSatVHFTransceiversParams {
	return &GetAvailableCubeSatVHFTransceiversParams{
		Context: ctx,
	}
}

// NewGetAvailableCubeSatVHFTransceiversParamsWithHTTPClient creates a new GetAvailableCubeSatVHFTransceiversParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAvailableCubeSatVHFTransceiversParamsWithHTTPClient(client *http.Client) *GetAvailableCubeSatVHFTransceiversParams {
	return &GetAvailableCubeSatVHFTransceiversParams{
		HTTPClient: client,
	}
}

/*
GetAvailableCubeSatVHFTransceiversParams contains all the parameters to send to the API endpoint

	for the get available cube sat v h f transceivers operation.

	Typically these are written to a http.Request.
*/
type GetAvailableCubeSatVHFTransceiversParams struct {

	/* FilterCubeSatVHFTransceiverByMaxFrequency.

	   Filter by maximum operating frequency
	*/
	FilterCubeSatVHFTransceiverByMaxFrequency *float64

	/* FilterCubeSatVHFTransceiverByMinFrequency.

	   Filter by minimum operating frequency
	*/
	FilterCubeSatVHFTransceiverByMinFrequency *float64

	/* Limit.

	   Limit for pagination
	*/
	Limit int64

	/* Offset.

	   Offset for pagination
	*/
	Offset int64

	/* SortField.

	   Sort parameters
	*/
	SortField *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get available cube sat v h f transceivers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAvailableCubeSatVHFTransceiversParams) WithDefaults() *GetAvailableCubeSatVHFTransceiversParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get available cube sat v h f transceivers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAvailableCubeSatVHFTransceiversParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithTimeout(timeout time.Duration) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithContext(ctx context.Context) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithHTTPClient(client *http.Client) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterCubeSatVHFTransceiverByMaxFrequency adds the filterCubeSatVHFTransceiverByMaxFrequency to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithFilterCubeSatVHFTransceiverByMaxFrequency(filterCubeSatVHFTransceiverByMaxFrequency *float64) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetFilterCubeSatVHFTransceiverByMaxFrequency(filterCubeSatVHFTransceiverByMaxFrequency)
	return o
}

// SetFilterCubeSatVHFTransceiverByMaxFrequency adds the filterCubeSatVHFTransceiverByMaxFrequency to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetFilterCubeSatVHFTransceiverByMaxFrequency(filterCubeSatVHFTransceiverByMaxFrequency *float64) {
	o.FilterCubeSatVHFTransceiverByMaxFrequency = filterCubeSatVHFTransceiverByMaxFrequency
}

// WithFilterCubeSatVHFTransceiverByMinFrequency adds the filterCubeSatVHFTransceiverByMinFrequency to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithFilterCubeSatVHFTransceiverByMinFrequency(filterCubeSatVHFTransceiverByMinFrequency *float64) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetFilterCubeSatVHFTransceiverByMinFrequency(filterCubeSatVHFTransceiverByMinFrequency)
	return o
}

// SetFilterCubeSatVHFTransceiverByMinFrequency adds the filterCubeSatVHFTransceiverByMinFrequency to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetFilterCubeSatVHFTransceiverByMinFrequency(filterCubeSatVHFTransceiverByMinFrequency *float64) {
	o.FilterCubeSatVHFTransceiverByMinFrequency = filterCubeSatVHFTransceiverByMinFrequency
}

// WithLimit adds the limit to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithLimit(limit int64) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithOffset(offset int64) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WithSortField adds the sortField to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) WithSortField(sortField *string) *GetAvailableCubeSatVHFTransceiversParams {
	o.SetSortField(sortField)
	return o
}

// SetSortField adds the sortField to the get available cube sat v h f transceivers params
func (o *GetAvailableCubeSatVHFTransceiversParams) SetSortField(sortField *string) {
	o.SortField = sortField
}

// WriteToRequest writes these params to a swagger request
func (o *GetAvailableCubeSatVHFTransceiversParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterCubeSatVHFTransceiverByMaxFrequency != nil {

		// query param FilterCubeSatVHFTransceiverByMaxFrequency
		var qrFilterCubeSatVHFTransceiverByMaxFrequency float64

		if o.FilterCubeSatVHFTransceiverByMaxFrequency != nil {
			qrFilterCubeSatVHFTransceiverByMaxFrequency = *o.FilterCubeSatVHFTransceiverByMaxFrequency
		}
		qFilterCubeSatVHFTransceiverByMaxFrequency := swag.FormatFloat64(qrFilterCubeSatVHFTransceiverByMaxFrequency)
		if qFilterCubeSatVHFTransceiverByMaxFrequency != "" {

			if err := r.SetQueryParam("FilterCubeSatVHFTransceiverByMaxFrequency", qFilterCubeSatVHFTransceiverByMaxFrequency); err != nil {
				return err
			}
		}
	}

	if o.FilterCubeSatVHFTransceiverByMinFrequency != nil {

		// query param FilterCubeSatVHFTransceiverByMinFrequency
		var qrFilterCubeSatVHFTransceiverByMinFrequency float64

		if o.FilterCubeSatVHFTransceiverByMinFrequency != nil {
			qrFilterCubeSatVHFTransceiverByMinFrequency = *o.FilterCubeSatVHFTransceiverByMinFrequency
		}
		qFilterCubeSatVHFTransceiverByMinFrequency := swag.FormatFloat64(qrFilterCubeSatVHFTransceiverByMinFrequency)
		if qFilterCubeSatVHFTransceiverByMinFrequency != "" {

			if err := r.SetQueryParam("FilterCubeSatVHFTransceiverByMinFrequency", qFilterCubeSatVHFTransceiverByMinFrequency); err != nil {
				return err
			}
		}
	}

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {

		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {

		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if o.SortField != nil {

		// query param sort[field]
		var qrSortField string

		if o.SortField != nil {
			qrSortField = *o.SortField
		}
		qSortField := qrSortField
		if qSortField != "" {

			if err := r.SetQueryParam("sort[field]", qSortField); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
