// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCubeSatSolarPanelsSideParams creates a new GetCubeSatSolarPanelsSideParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCubeSatSolarPanelsSideParams() *GetCubeSatSolarPanelsSideParams {
	return &GetCubeSatSolarPanelsSideParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCubeSatSolarPanelsSideParamsWithTimeout creates a new GetCubeSatSolarPanelsSideParams object
// with the ability to set a timeout on a request.
func NewGetCubeSatSolarPanelsSideParamsWithTimeout(timeout time.Duration) *GetCubeSatSolarPanelsSideParams {
	return &GetCubeSatSolarPanelsSideParams{
		timeout: timeout,
	}
}

// NewGetCubeSatSolarPanelsSideParamsWithContext creates a new GetCubeSatSolarPanelsSideParams object
// with the ability to set a context for a request.
func NewGetCubeSatSolarPanelsSideParamsWithContext(ctx context.Context) *GetCubeSatSolarPanelsSideParams {
	return &GetCubeSatSolarPanelsSideParams{
		Context: ctx,
	}
}

// NewGetCubeSatSolarPanelsSideParamsWithHTTPClient creates a new GetCubeSatSolarPanelsSideParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCubeSatSolarPanelsSideParamsWithHTTPClient(client *http.Client) *GetCubeSatSolarPanelsSideParams {
	return &GetCubeSatSolarPanelsSideParams{
		HTTPClient: client,
	}
}

/*
GetCubeSatSolarPanelsSideParams contains all the parameters to send to the API endpoint

	for the get cube sat solar panels side operation.

	Typically these are written to a http.Request.
*/
type GetCubeSatSolarPanelsSideParams struct {

	/* FilterCubeSatSolarPanelByLengthMax.

	   Filter By Max Length
	*/
	FilterCubeSatSolarPanelByLengthMax *float64

	/* FilterCubeSatSolarPanelByLengthMin.

	   Filter By Min Length
	*/
	FilterCubeSatSolarPanelByLengthMin *float64

	/* Limit.

	   Offset Configs
	*/
	Limit int64

	/* Offset.

	   Offset Configs
	*/
	Offset int64

	/* SortField.

	   sort parametrs
	*/
	SortField *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cube sat solar panels side params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCubeSatSolarPanelsSideParams) WithDefaults() *GetCubeSatSolarPanelsSideParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cube sat solar panels side params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCubeSatSolarPanelsSideParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithTimeout(timeout time.Duration) *GetCubeSatSolarPanelsSideParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithContext(ctx context.Context) *GetCubeSatSolarPanelsSideParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithHTTPClient(client *http.Client) *GetCubeSatSolarPanelsSideParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterCubeSatSolarPanelByLengthMax adds the filterCubeSatSolarPanelByLengthMax to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithFilterCubeSatSolarPanelByLengthMax(filterCubeSatSolarPanelByLengthMax *float64) *GetCubeSatSolarPanelsSideParams {
	o.SetFilterCubeSatSolarPanelByLengthMax(filterCubeSatSolarPanelByLengthMax)
	return o
}

// SetFilterCubeSatSolarPanelByLengthMax adds the filterCubeSatSolarPanelByLengthMax to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetFilterCubeSatSolarPanelByLengthMax(filterCubeSatSolarPanelByLengthMax *float64) {
	o.FilterCubeSatSolarPanelByLengthMax = filterCubeSatSolarPanelByLengthMax
}

// WithFilterCubeSatSolarPanelByLengthMin adds the filterCubeSatSolarPanelByLengthMin to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithFilterCubeSatSolarPanelByLengthMin(filterCubeSatSolarPanelByLengthMin *float64) *GetCubeSatSolarPanelsSideParams {
	o.SetFilterCubeSatSolarPanelByLengthMin(filterCubeSatSolarPanelByLengthMin)
	return o
}

// SetFilterCubeSatSolarPanelByLengthMin adds the filterCubeSatSolarPanelByLengthMin to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetFilterCubeSatSolarPanelByLengthMin(filterCubeSatSolarPanelByLengthMin *float64) {
	o.FilterCubeSatSolarPanelByLengthMin = filterCubeSatSolarPanelByLengthMin
}

// WithLimit adds the limit to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithLimit(limit int64) *GetCubeSatSolarPanelsSideParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetLimit(limit int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithOffset(offset int64) *GetCubeSatSolarPanelsSideParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetOffset(offset int64) {
	o.Offset = offset
}

// WithSortField adds the sortField to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) WithSortField(sortField *string) *GetCubeSatSolarPanelsSideParams {
	o.SetSortField(sortField)
	return o
}

// SetSortField adds the sortField to the get cube sat solar panels side params
func (o *GetCubeSatSolarPanelsSideParams) SetSortField(sortField *string) {
	o.SortField = sortField
}

// WriteToRequest writes these params to a swagger request
func (o *GetCubeSatSolarPanelsSideParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterCubeSatSolarPanelByLengthMax != nil {

		// query param FilterCubeSatSolarPanelByLength[max]
		var qrFilterCubeSatSolarPanelByLengthMax float64

		if o.FilterCubeSatSolarPanelByLengthMax != nil {
			qrFilterCubeSatSolarPanelByLengthMax = *o.FilterCubeSatSolarPanelByLengthMax
		}
		qFilterCubeSatSolarPanelByLengthMax := swag.FormatFloat64(qrFilterCubeSatSolarPanelByLengthMax)
		if qFilterCubeSatSolarPanelByLengthMax != "" {

			if err := r.SetQueryParam("FilterCubeSatSolarPanelByLength[max]", qFilterCubeSatSolarPanelByLengthMax); err != nil {
				return err
			}
		}
	}

	if o.FilterCubeSatSolarPanelByLengthMin != nil {

		// query param FilterCubeSatSolarPanelByLength[min]
		var qrFilterCubeSatSolarPanelByLengthMin float64

		if o.FilterCubeSatSolarPanelByLengthMin != nil {
			qrFilterCubeSatSolarPanelByLengthMin = *o.FilterCubeSatSolarPanelByLengthMin
		}
		qFilterCubeSatSolarPanelByLengthMin := swag.FormatFloat64(qrFilterCubeSatSolarPanelByLengthMin)
		if qFilterCubeSatSolarPanelByLengthMin != "" {

			if err := r.SetQueryParam("FilterCubeSatSolarPanelByLength[min]", qFilterCubeSatSolarPanelByLengthMin); err != nil {
				return err
			}
		}
	}

	// query param limit
	qrLimit := o.Limit
	qLimit := swag.FormatInt64(qrLimit)
	if qLimit != "" {

		if err := r.SetQueryParam("limit", qLimit); err != nil {
			return err
		}
	}

	// query param offset
	qrOffset := o.Offset
	qOffset := swag.FormatInt64(qrOffset)
	if qOffset != "" {

		if err := r.SetQueryParam("offset", qOffset); err != nil {
			return err
		}
	}

	if o.SortField != nil {

		// query param sort[field]
		var qrSortField string

		if o.SortField != nil {
			qrSortField = *o.SortField
		}
		qSortField := qrSortField
		if qSortField != "" {

			if err := r.SetQueryParam("sort[field]", qSortField); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
