// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// NewLoginAdminParams creates a new LoginAdminParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLoginAdminParams() *LoginAdminParams {
	return &LoginAdminParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLoginAdminParamsWithTimeout creates a new LoginAdminParams object
// with the ability to set a timeout on a request.
func NewLoginAdminParamsWithTimeout(timeout time.Duration) *LoginAdminParams {
	return &LoginAdminParams{
		timeout: timeout,
	}
}

// NewLoginAdminParamsWithContext creates a new LoginAdminParams object
// with the ability to set a context for a request.
func NewLoginAdminParamsWithContext(ctx context.Context) *LoginAdminParams {
	return &LoginAdminParams{
		Context: ctx,
	}
}

// NewLoginAdminParamsWithHTTPClient creates a new LoginAdminParams object
// with the ability to set a custom HTTPClient for a request.
func NewLoginAdminParamsWithHTTPClient(client *http.Client) *LoginAdminParams {
	return &LoginAdminParams{
		HTTPClient: client,
	}
}

/*
LoginAdminParams contains all the parameters to send to the API endpoint

	for the login admin operation.

	Typically these are written to a http.Request.
*/
type LoginAdminParams struct {

	/* LoginAdmin.

	   Login Admin Body
	*/
	LoginAdmin *models.LoginAdmin

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the login admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoginAdminParams) WithDefaults() *LoginAdminParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the login admin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LoginAdminParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the login admin params
func (o *LoginAdminParams) WithTimeout(timeout time.Duration) *LoginAdminParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login admin params
func (o *LoginAdminParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login admin params
func (o *LoginAdminParams) WithContext(ctx context.Context) *LoginAdminParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login admin params
func (o *LoginAdminParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login admin params
func (o *LoginAdminParams) WithHTTPClient(client *http.Client) *LoginAdminParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login admin params
func (o *LoginAdminParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLoginAdmin adds the loginAdmin to the login admin params
func (o *LoginAdminParams) WithLoginAdmin(loginAdmin *models.LoginAdmin) *LoginAdminParams {
	o.SetLoginAdmin(loginAdmin)
	return o
}

// SetLoginAdmin adds the loginAdmin to the login admin params
func (o *LoginAdminParams) SetLoginAdmin(loginAdmin *models.LoginAdmin) {
	o.LoginAdmin = loginAdmin
}

// WriteToRequest writes these params to a swagger request
func (o *LoginAdminParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.LoginAdmin != nil {
		if err := r.SetBodyParam(o.LoginAdmin); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
