// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// CreateSolarPanelTopOKCode is the HTTP code returned for type CreateSolarPanelTopOK
const CreateSolarPanelTopOKCode int = 200

/*
CreateSolarPanelTopOK Create Solar Panel Top Response

swagger:response createSolarPanelTopOK
*/
type CreateSolarPanelTopOK struct {

	/*
	  In: Body
	*/
	Payload *models.SolarPanelTop `json:"body,omitempty"`
}

// NewCreateSolarPanelTopOK creates CreateSolarPanelTopOK with default headers values
func NewCreateSolarPanelTopOK() *CreateSolarPanelTopOK {

	return &CreateSolarPanelTopOK{}
}

// WithPayload adds the payload to the create solar panel top o k response
func (o *CreateSolarPanelTopOK) WithPayload(payload *models.SolarPanelTop) *CreateSolarPanelTopOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create solar panel top o k response
func (o *CreateSolarPanelTopOK) SetPayload(payload *models.SolarPanelTop) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSolarPanelTopOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSolarPanelTopBadRequestCode is the HTTP code returned for type CreateSolarPanelTopBadRequest
const CreateSolarPanelTopBadRequestCode int = 400

/*
CreateSolarPanelTopBadRequest Bad request

swagger:response createSolarPanelTopBadRequest
*/
type CreateSolarPanelTopBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSolarPanelTopBadRequest creates CreateSolarPanelTopBadRequest with default headers values
func NewCreateSolarPanelTopBadRequest() *CreateSolarPanelTopBadRequest {

	return &CreateSolarPanelTopBadRequest{}
}

// WithPayload adds the payload to the create solar panel top bad request response
func (o *CreateSolarPanelTopBadRequest) WithPayload(payload *models.Error) *CreateSolarPanelTopBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create solar panel top bad request response
func (o *CreateSolarPanelTopBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSolarPanelTopBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSolarPanelTopForbiddenCode is the HTTP code returned for type CreateSolarPanelTopForbidden
const CreateSolarPanelTopForbiddenCode int = 403

/*
CreateSolarPanelTopForbidden Forbidden

swagger:response createSolarPanelTopForbidden
*/
type CreateSolarPanelTopForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSolarPanelTopForbidden creates CreateSolarPanelTopForbidden with default headers values
func NewCreateSolarPanelTopForbidden() *CreateSolarPanelTopForbidden {

	return &CreateSolarPanelTopForbidden{}
}

// WithPayload adds the payload to the create solar panel top forbidden response
func (o *CreateSolarPanelTopForbidden) WithPayload(payload *models.Error) *CreateSolarPanelTopForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create solar panel top forbidden response
func (o *CreateSolarPanelTopForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSolarPanelTopForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSolarPanelTopUnprocessableEntityCode is the HTTP code returned for type CreateSolarPanelTopUnprocessableEntity
const CreateSolarPanelTopUnprocessableEntityCode int = 422

/*
CreateSolarPanelTopUnprocessableEntity Unprocessable Entity

swagger:response createSolarPanelTopUnprocessableEntity
*/
type CreateSolarPanelTopUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSolarPanelTopUnprocessableEntity creates CreateSolarPanelTopUnprocessableEntity with default headers values
func NewCreateSolarPanelTopUnprocessableEntity() *CreateSolarPanelTopUnprocessableEntity {

	return &CreateSolarPanelTopUnprocessableEntity{}
}

// WithPayload adds the payload to the create solar panel top unprocessable entity response
func (o *CreateSolarPanelTopUnprocessableEntity) WithPayload(payload *models.Error) *CreateSolarPanelTopUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create solar panel top unprocessable entity response
func (o *CreateSolarPanelTopUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSolarPanelTopUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSolarPanelTopInternalServerErrorCode is the HTTP code returned for type CreateSolarPanelTopInternalServerError
const CreateSolarPanelTopInternalServerErrorCode int = 500

/*
CreateSolarPanelTopInternalServerError Internal server error

swagger:response createSolarPanelTopInternalServerError
*/
type CreateSolarPanelTopInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSolarPanelTopInternalServerError creates CreateSolarPanelTopInternalServerError with default headers values
func NewCreateSolarPanelTopInternalServerError() *CreateSolarPanelTopInternalServerError {

	return &CreateSolarPanelTopInternalServerError{}
}

// WithPayload adds the payload to the create solar panel top internal server error response
func (o *CreateSolarPanelTopInternalServerError) WithPayload(payload *models.Error) *CreateSolarPanelTopInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create solar panel top internal server error response
func (o *CreateSolarPanelTopInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSolarPanelTopInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
