// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// CreateCubeSatProjectHandlerFunc turns a function with the right signature into a create cube sat project handler
type CreateCubeSatProjectHandlerFunc func(CreateCubeSatProjectParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCubeSatProjectHandlerFunc) Handle(params CreateCubeSatProjectParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateCubeSatProjectHandler interface for that can handle valid create cube sat project params
type CreateCubeSatProjectHandler interface {
	Handle(CreateCubeSatProjectParams, *models.Principal) middleware.Responder
}

// NewCreateCubeSatProject creates a new http.Handler for the create cube sat project operation
func NewCreateCubeSatProject(ctx *middleware.Context, handler CreateCubeSatProjectHandler) *CreateCubeSatProject {
	return &CreateCubeSatProject{Context: ctx, Handler: handler}
}

/*
	CreateCubeSatProject swagger:route POST /cube_sat_project CubeSatProject createCubeSatProject

Create CubeSat project
*/
type CreateCubeSatProject struct {
	Context *middleware.Context
	Handler CreateCubeSatProjectHandler
}

func (o *CreateCubeSatProject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCubeSatProjectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
