// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// CreatePowerSystemOKCode is the HTTP code returned for type CreatePowerSystemOK
const CreatePowerSystemOKCode int = 200

/*
CreatePowerSystemOK Create Power System Response

swagger:response createPowerSystemOK
*/
type CreatePowerSystemOK struct {

	/*
	  In: Body
	*/
	Payload *models.CubeSatPowerSystem `json:"body,omitempty"`
}

// NewCreatePowerSystemOK creates CreatePowerSystemOK with default headers values
func NewCreatePowerSystemOK() *CreatePowerSystemOK {

	return &CreatePowerSystemOK{}
}

// WithPayload adds the payload to the create power system o k response
func (o *CreatePowerSystemOK) WithPayload(payload *models.CubeSatPowerSystem) *CreatePowerSystemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create power system o k response
func (o *CreatePowerSystemOK) SetPayload(payload *models.CubeSatPowerSystem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePowerSystemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePowerSystemBadRequestCode is the HTTP code returned for type CreatePowerSystemBadRequest
const CreatePowerSystemBadRequestCode int = 400

/*
CreatePowerSystemBadRequest Bad request

swagger:response createPowerSystemBadRequest
*/
type CreatePowerSystemBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePowerSystemBadRequest creates CreatePowerSystemBadRequest with default headers values
func NewCreatePowerSystemBadRequest() *CreatePowerSystemBadRequest {

	return &CreatePowerSystemBadRequest{}
}

// WithPayload adds the payload to the create power system bad request response
func (o *CreatePowerSystemBadRequest) WithPayload(payload *models.Error) *CreatePowerSystemBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create power system bad request response
func (o *CreatePowerSystemBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePowerSystemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePowerSystemForbiddenCode is the HTTP code returned for type CreatePowerSystemForbidden
const CreatePowerSystemForbiddenCode int = 403

/*
CreatePowerSystemForbidden Forbidden

swagger:response createPowerSystemForbidden
*/
type CreatePowerSystemForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePowerSystemForbidden creates CreatePowerSystemForbidden with default headers values
func NewCreatePowerSystemForbidden() *CreatePowerSystemForbidden {

	return &CreatePowerSystemForbidden{}
}

// WithPayload adds the payload to the create power system forbidden response
func (o *CreatePowerSystemForbidden) WithPayload(payload *models.Error) *CreatePowerSystemForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create power system forbidden response
func (o *CreatePowerSystemForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePowerSystemForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePowerSystemUnprocessableEntityCode is the HTTP code returned for type CreatePowerSystemUnprocessableEntity
const CreatePowerSystemUnprocessableEntityCode int = 422

/*
CreatePowerSystemUnprocessableEntity Unprocessable Entity

swagger:response createPowerSystemUnprocessableEntity
*/
type CreatePowerSystemUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePowerSystemUnprocessableEntity creates CreatePowerSystemUnprocessableEntity with default headers values
func NewCreatePowerSystemUnprocessableEntity() *CreatePowerSystemUnprocessableEntity {

	return &CreatePowerSystemUnprocessableEntity{}
}

// WithPayload adds the payload to the create power system unprocessable entity response
func (o *CreatePowerSystemUnprocessableEntity) WithPayload(payload *models.Error) *CreatePowerSystemUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create power system unprocessable entity response
func (o *CreatePowerSystemUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePowerSystemUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePowerSystemInternalServerErrorCode is the HTTP code returned for type CreatePowerSystemInternalServerError
const CreatePowerSystemInternalServerErrorCode int = 500

/*
CreatePowerSystemInternalServerError Internal server error

swagger:response createPowerSystemInternalServerError
*/
type CreatePowerSystemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePowerSystemInternalServerError creates CreatePowerSystemInternalServerError with default headers values
func NewCreatePowerSystemInternalServerError() *CreatePowerSystemInternalServerError {

	return &CreatePowerSystemInternalServerError{}
}

// WithPayload adds the payload to the create power system internal server error response
func (o *CreatePowerSystemInternalServerError) WithPayload(payload *models.Error) *CreatePowerSystemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create power system internal server error response
func (o *CreatePowerSystemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePowerSystemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
