// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// CreateCubeSatVHFTransceiverOKCode is the HTTP code returned for type CreateCubeSatVHFTransceiverOK
const CreateCubeSatVHFTransceiverOKCode int = 200

/*
CreateCubeSatVHFTransceiverOK Create CubeSat VHF Transceiver Response

swagger:response createCubeSatVHFTransceiverOK
*/
type CreateCubeSatVHFTransceiverOK struct {

	/*
	  In: Body
	*/
	Payload *models.VHFTransceiver `json:"body,omitempty"`
}

// NewCreateCubeSatVHFTransceiverOK creates CreateCubeSatVHFTransceiverOK with default headers values
func NewCreateCubeSatVHFTransceiverOK() *CreateCubeSatVHFTransceiverOK {

	return &CreateCubeSatVHFTransceiverOK{}
}

// WithPayload adds the payload to the create cube sat v h f transceiver o k response
func (o *CreateCubeSatVHFTransceiverOK) WithPayload(payload *models.VHFTransceiver) *CreateCubeSatVHFTransceiverOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cube sat v h f transceiver o k response
func (o *CreateCubeSatVHFTransceiverOK) SetPayload(payload *models.VHFTransceiver) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCubeSatVHFTransceiverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCubeSatVHFTransceiverBadRequestCode is the HTTP code returned for type CreateCubeSatVHFTransceiverBadRequest
const CreateCubeSatVHFTransceiverBadRequestCode int = 400

/*
CreateCubeSatVHFTransceiverBadRequest Bad request

swagger:response createCubeSatVHFTransceiverBadRequest
*/
type CreateCubeSatVHFTransceiverBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCubeSatVHFTransceiverBadRequest creates CreateCubeSatVHFTransceiverBadRequest with default headers values
func NewCreateCubeSatVHFTransceiverBadRequest() *CreateCubeSatVHFTransceiverBadRequest {

	return &CreateCubeSatVHFTransceiverBadRequest{}
}

// WithPayload adds the payload to the create cube sat v h f transceiver bad request response
func (o *CreateCubeSatVHFTransceiverBadRequest) WithPayload(payload *models.Error) *CreateCubeSatVHFTransceiverBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cube sat v h f transceiver bad request response
func (o *CreateCubeSatVHFTransceiverBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCubeSatVHFTransceiverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCubeSatVHFTransceiverForbiddenCode is the HTTP code returned for type CreateCubeSatVHFTransceiverForbidden
const CreateCubeSatVHFTransceiverForbiddenCode int = 403

/*
CreateCubeSatVHFTransceiverForbidden Forbidden

swagger:response createCubeSatVHFTransceiverForbidden
*/
type CreateCubeSatVHFTransceiverForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCubeSatVHFTransceiverForbidden creates CreateCubeSatVHFTransceiverForbidden with default headers values
func NewCreateCubeSatVHFTransceiverForbidden() *CreateCubeSatVHFTransceiverForbidden {

	return &CreateCubeSatVHFTransceiverForbidden{}
}

// WithPayload adds the payload to the create cube sat v h f transceiver forbidden response
func (o *CreateCubeSatVHFTransceiverForbidden) WithPayload(payload *models.Error) *CreateCubeSatVHFTransceiverForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cube sat v h f transceiver forbidden response
func (o *CreateCubeSatVHFTransceiverForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCubeSatVHFTransceiverForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCubeSatVHFTransceiverUnprocessableEntityCode is the HTTP code returned for type CreateCubeSatVHFTransceiverUnprocessableEntity
const CreateCubeSatVHFTransceiverUnprocessableEntityCode int = 422

/*
CreateCubeSatVHFTransceiverUnprocessableEntity Unprocessable Entity

swagger:response createCubeSatVHFTransceiverUnprocessableEntity
*/
type CreateCubeSatVHFTransceiverUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCubeSatVHFTransceiverUnprocessableEntity creates CreateCubeSatVHFTransceiverUnprocessableEntity with default headers values
func NewCreateCubeSatVHFTransceiverUnprocessableEntity() *CreateCubeSatVHFTransceiverUnprocessableEntity {

	return &CreateCubeSatVHFTransceiverUnprocessableEntity{}
}

// WithPayload adds the payload to the create cube sat v h f transceiver unprocessable entity response
func (o *CreateCubeSatVHFTransceiverUnprocessableEntity) WithPayload(payload *models.Error) *CreateCubeSatVHFTransceiverUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cube sat v h f transceiver unprocessable entity response
func (o *CreateCubeSatVHFTransceiverUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCubeSatVHFTransceiverUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCubeSatVHFTransceiverInternalServerErrorCode is the HTTP code returned for type CreateCubeSatVHFTransceiverInternalServerError
const CreateCubeSatVHFTransceiverInternalServerErrorCode int = 500

/*
CreateCubeSatVHFTransceiverInternalServerError Internal server error

swagger:response createCubeSatVHFTransceiverInternalServerError
*/
type CreateCubeSatVHFTransceiverInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateCubeSatVHFTransceiverInternalServerError creates CreateCubeSatVHFTransceiverInternalServerError with default headers values
func NewCreateCubeSatVHFTransceiverInternalServerError() *CreateCubeSatVHFTransceiverInternalServerError {

	return &CreateCubeSatVHFTransceiverInternalServerError{}
}

// WithPayload adds the payload to the create cube sat v h f transceiver internal server error response
func (o *CreateCubeSatVHFTransceiverInternalServerError) WithPayload(payload *models.Error) *CreateCubeSatVHFTransceiverInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create cube sat v h f transceiver internal server error response
func (o *CreateCubeSatVHFTransceiverInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCubeSatVHFTransceiverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
