// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// GetCubeSatPowerSystemsHandlerFunc turns a function with the right signature into a get cube sat power systems handler
type GetCubeSatPowerSystemsHandlerFunc func(GetCubeSatPowerSystemsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCubeSatPowerSystemsHandlerFunc) Handle(params GetCubeSatPowerSystemsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCubeSatPowerSystemsHandler interface for that can handle valid get cube sat power systems params
type GetCubeSatPowerSystemsHandler interface {
	Handle(GetCubeSatPowerSystemsParams, *models.Principal) middleware.Responder
}

// NewGetCubeSatPowerSystems creates a new http.Handler for the get cube sat power systems operation
func NewGetCubeSatPowerSystems(ctx *middleware.Context, handler GetCubeSatPowerSystemsHandler) *GetCubeSatPowerSystems {
	return &GetCubeSatPowerSystems{Context: ctx, Handler: handler}
}

/*
	GetCubeSatPowerSystems swagger:route GET /cube_sat_power_system/available_power_systems PowerSystem getCubeSatPowerSystems

Get Cube Sat Power Systems
*/
type GetCubeSatPowerSystems struct {
	Context *middleware.Context
	Handler GetCubeSatPowerSystemsHandler
}

func (o *GetCubeSatPowerSystems) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCubeSatPowerSystemsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
