// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetAvailableCubeSatVHTransceiversURL generates an URL for the get available cube sat v h transceivers operation
type GetAvailableCubeSatVHTransceiversURL struct {
	FilterCubeSatVHFTransceiverByMaxFrequency *float64
	FilterCubeSatVHFTransceiverByMinFrequency *float64
	Limit                                     int64
	Offset                                    int64
	SortField                                 *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAvailableCubeSatVHTransceiversURL) WithBasePath(bp string) *GetAvailableCubeSatVHTransceiversURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAvailableCubeSatVHTransceiversURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetAvailableCubeSatVHTransceiversURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/cube_sat_vhf_transceiver/available"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var filterCubeSatVHFTransceiverByMaxFrequencyQ string
	if o.FilterCubeSatVHFTransceiverByMaxFrequency != nil {
		filterCubeSatVHFTransceiverByMaxFrequencyQ = swag.FormatFloat64(*o.FilterCubeSatVHFTransceiverByMaxFrequency)
	}
	if filterCubeSatVHFTransceiverByMaxFrequencyQ != "" {
		qs.Set("FilterCubeSatVHFTransceiverByMaxFrequency", filterCubeSatVHFTransceiverByMaxFrequencyQ)
	}

	var filterCubeSatVHFTransceiverByMinFrequencyQ string
	if o.FilterCubeSatVHFTransceiverByMinFrequency != nil {
		filterCubeSatVHFTransceiverByMinFrequencyQ = swag.FormatFloat64(*o.FilterCubeSatVHFTransceiverByMinFrequency)
	}
	if filterCubeSatVHFTransceiverByMinFrequencyQ != "" {
		qs.Set("FilterCubeSatVHFTransceiverByMinFrequency", filterCubeSatVHFTransceiverByMinFrequencyQ)
	}

	limitQ := swag.FormatInt64(o.Limit)
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	offsetQ := swag.FormatInt64(o.Offset)
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	var sortFieldQ string
	if o.SortField != nil {
		sortFieldQ = *o.SortField
	}
	if sortFieldQ != "" {
		qs.Set("sort[field]", sortFieldQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetAvailableCubeSatVHTransceiversURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetAvailableCubeSatVHTransceiversURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetAvailableCubeSatVHTransceiversURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetAvailableCubeSatVHTransceiversURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetAvailableCubeSatVHTransceiversURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetAvailableCubeSatVHTransceiversURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
