// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// LoadTestDataHandlerFunc turns a function with the right signature into a load test data handler
type LoadTestDataHandlerFunc func(LoadTestDataParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn LoadTestDataHandlerFunc) Handle(params LoadTestDataParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// LoadTestDataHandler interface for that can handle valid load test data params
type LoadTestDataHandler interface {
	Handle(LoadTestDataParams, *models.Principal) middleware.Responder
}

// NewLoadTestData creates a new http.Handler for the load test data operation
func NewLoadTestData(ctx *middleware.Context, handler LoadTestDataHandler) *LoadTestData {
	return &LoadTestData{Context: ctx, Handler: handler}
}

/*
	LoadTestData swagger:route GET /test_data_load TestData loadTestData

Load Test Data
*/
type LoadTestData struct {
	Context *middleware.Context
	Handler LoadTestDataHandler
}

func (o *LoadTestData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLoadTestDataParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
