// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// UpdateCubeSatSolarPanelSideOKCode is the HTTP code returned for type UpdateCubeSatSolarPanelSideOK
const UpdateCubeSatSolarPanelSideOKCode int = 200

/*
UpdateCubeSatSolarPanelSideOK Update Solar Panel Side Response

swagger:response updateCubeSatSolarPanelSideOK
*/
type UpdateCubeSatSolarPanelSideOK struct {

	/*
	  In: Body
	*/
	Payload *models.SolarPanelSide `json:"body,omitempty"`
}

// NewUpdateCubeSatSolarPanelSideOK creates UpdateCubeSatSolarPanelSideOK with default headers values
func NewUpdateCubeSatSolarPanelSideOK() *UpdateCubeSatSolarPanelSideOK {

	return &UpdateCubeSatSolarPanelSideOK{}
}

// WithPayload adds the payload to the update cube sat solar panel side o k response
func (o *UpdateCubeSatSolarPanelSideOK) WithPayload(payload *models.SolarPanelSide) *UpdateCubeSatSolarPanelSideOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat solar panel side o k response
func (o *UpdateCubeSatSolarPanelSideOK) SetPayload(payload *models.SolarPanelSide) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatSolarPanelSideOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatSolarPanelSideBadRequestCode is the HTTP code returned for type UpdateCubeSatSolarPanelSideBadRequest
const UpdateCubeSatSolarPanelSideBadRequestCode int = 400

/*
UpdateCubeSatSolarPanelSideBadRequest Bad request

swagger:response updateCubeSatSolarPanelSideBadRequest
*/
type UpdateCubeSatSolarPanelSideBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatSolarPanelSideBadRequest creates UpdateCubeSatSolarPanelSideBadRequest with default headers values
func NewUpdateCubeSatSolarPanelSideBadRequest() *UpdateCubeSatSolarPanelSideBadRequest {

	return &UpdateCubeSatSolarPanelSideBadRequest{}
}

// WithPayload adds the payload to the update cube sat solar panel side bad request response
func (o *UpdateCubeSatSolarPanelSideBadRequest) WithPayload(payload *models.Error) *UpdateCubeSatSolarPanelSideBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat solar panel side bad request response
func (o *UpdateCubeSatSolarPanelSideBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatSolarPanelSideBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatSolarPanelSideForbiddenCode is the HTTP code returned for type UpdateCubeSatSolarPanelSideForbidden
const UpdateCubeSatSolarPanelSideForbiddenCode int = 403

/*
UpdateCubeSatSolarPanelSideForbidden Forbidden

swagger:response updateCubeSatSolarPanelSideForbidden
*/
type UpdateCubeSatSolarPanelSideForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatSolarPanelSideForbidden creates UpdateCubeSatSolarPanelSideForbidden with default headers values
func NewUpdateCubeSatSolarPanelSideForbidden() *UpdateCubeSatSolarPanelSideForbidden {

	return &UpdateCubeSatSolarPanelSideForbidden{}
}

// WithPayload adds the payload to the update cube sat solar panel side forbidden response
func (o *UpdateCubeSatSolarPanelSideForbidden) WithPayload(payload *models.Error) *UpdateCubeSatSolarPanelSideForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat solar panel side forbidden response
func (o *UpdateCubeSatSolarPanelSideForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatSolarPanelSideForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatSolarPanelSideUnprocessableEntityCode is the HTTP code returned for type UpdateCubeSatSolarPanelSideUnprocessableEntity
const UpdateCubeSatSolarPanelSideUnprocessableEntityCode int = 422

/*
UpdateCubeSatSolarPanelSideUnprocessableEntity Unprocessable Entity

swagger:response updateCubeSatSolarPanelSideUnprocessableEntity
*/
type UpdateCubeSatSolarPanelSideUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatSolarPanelSideUnprocessableEntity creates UpdateCubeSatSolarPanelSideUnprocessableEntity with default headers values
func NewUpdateCubeSatSolarPanelSideUnprocessableEntity() *UpdateCubeSatSolarPanelSideUnprocessableEntity {

	return &UpdateCubeSatSolarPanelSideUnprocessableEntity{}
}

// WithPayload adds the payload to the update cube sat solar panel side unprocessable entity response
func (o *UpdateCubeSatSolarPanelSideUnprocessableEntity) WithPayload(payload *models.Error) *UpdateCubeSatSolarPanelSideUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat solar panel side unprocessable entity response
func (o *UpdateCubeSatSolarPanelSideUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatSolarPanelSideUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatSolarPanelSideInternalServerErrorCode is the HTTP code returned for type UpdateCubeSatSolarPanelSideInternalServerError
const UpdateCubeSatSolarPanelSideInternalServerErrorCode int = 500

/*
UpdateCubeSatSolarPanelSideInternalServerError Internal server error

swagger:response updateCubeSatSolarPanelSideInternalServerError
*/
type UpdateCubeSatSolarPanelSideInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatSolarPanelSideInternalServerError creates UpdateCubeSatSolarPanelSideInternalServerError with default headers values
func NewUpdateCubeSatSolarPanelSideInternalServerError() *UpdateCubeSatSolarPanelSideInternalServerError {

	return &UpdateCubeSatSolarPanelSideInternalServerError{}
}

// WithPayload adds the payload to the update cube sat solar panel side internal server error response
func (o *UpdateCubeSatSolarPanelSideInternalServerError) WithPayload(payload *models.Error) *UpdateCubeSatSolarPanelSideInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat solar panel side internal server error response
func (o *UpdateCubeSatSolarPanelSideInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatSolarPanelSideInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
