// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// UpdateCubeSatVHFTransceiverOKCode is the HTTP code returned for type UpdateCubeSatVHFTransceiverOK
const UpdateCubeSatVHFTransceiverOKCode int = 200

/*
UpdateCubeSatVHFTransceiverOK Update CubeSat VHF Transceiver Response

swagger:response updateCubeSatVHFTransceiverOK
*/
type UpdateCubeSatVHFTransceiverOK struct {

	/*
	  In: Body
	*/
	Payload *models.VHFTransceiver `json:"body,omitempty"`
}

// NewUpdateCubeSatVHFTransceiverOK creates UpdateCubeSatVHFTransceiverOK with default headers values
func NewUpdateCubeSatVHFTransceiverOK() *UpdateCubeSatVHFTransceiverOK {

	return &UpdateCubeSatVHFTransceiverOK{}
}

// WithPayload adds the payload to the update cube sat v h f transceiver o k response
func (o *UpdateCubeSatVHFTransceiverOK) WithPayload(payload *models.VHFTransceiver) *UpdateCubeSatVHFTransceiverOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat v h f transceiver o k response
func (o *UpdateCubeSatVHFTransceiverOK) SetPayload(payload *models.VHFTransceiver) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatVHFTransceiverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatVHFTransceiverBadRequestCode is the HTTP code returned for type UpdateCubeSatVHFTransceiverBadRequest
const UpdateCubeSatVHFTransceiverBadRequestCode int = 400

/*
UpdateCubeSatVHFTransceiverBadRequest Bad request

swagger:response updateCubeSatVHFTransceiverBadRequest
*/
type UpdateCubeSatVHFTransceiverBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatVHFTransceiverBadRequest creates UpdateCubeSatVHFTransceiverBadRequest with default headers values
func NewUpdateCubeSatVHFTransceiverBadRequest() *UpdateCubeSatVHFTransceiverBadRequest {

	return &UpdateCubeSatVHFTransceiverBadRequest{}
}

// WithPayload adds the payload to the update cube sat v h f transceiver bad request response
func (o *UpdateCubeSatVHFTransceiverBadRequest) WithPayload(payload *models.Error) *UpdateCubeSatVHFTransceiverBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat v h f transceiver bad request response
func (o *UpdateCubeSatVHFTransceiverBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatVHFTransceiverBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatVHFTransceiverForbiddenCode is the HTTP code returned for type UpdateCubeSatVHFTransceiverForbidden
const UpdateCubeSatVHFTransceiverForbiddenCode int = 403

/*
UpdateCubeSatVHFTransceiverForbidden Forbidden

swagger:response updateCubeSatVHFTransceiverForbidden
*/
type UpdateCubeSatVHFTransceiverForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatVHFTransceiverForbidden creates UpdateCubeSatVHFTransceiverForbidden with default headers values
func NewUpdateCubeSatVHFTransceiverForbidden() *UpdateCubeSatVHFTransceiverForbidden {

	return &UpdateCubeSatVHFTransceiverForbidden{}
}

// WithPayload adds the payload to the update cube sat v h f transceiver forbidden response
func (o *UpdateCubeSatVHFTransceiverForbidden) WithPayload(payload *models.Error) *UpdateCubeSatVHFTransceiverForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat v h f transceiver forbidden response
func (o *UpdateCubeSatVHFTransceiverForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatVHFTransceiverForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatVHFTransceiverUnprocessableEntityCode is the HTTP code returned for type UpdateCubeSatVHFTransceiverUnprocessableEntity
const UpdateCubeSatVHFTransceiverUnprocessableEntityCode int = 422

/*
UpdateCubeSatVHFTransceiverUnprocessableEntity Unprocessable Entity

swagger:response updateCubeSatVHFTransceiverUnprocessableEntity
*/
type UpdateCubeSatVHFTransceiverUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatVHFTransceiverUnprocessableEntity creates UpdateCubeSatVHFTransceiverUnprocessableEntity with default headers values
func NewUpdateCubeSatVHFTransceiverUnprocessableEntity() *UpdateCubeSatVHFTransceiverUnprocessableEntity {

	return &UpdateCubeSatVHFTransceiverUnprocessableEntity{}
}

// WithPayload adds the payload to the update cube sat v h f transceiver unprocessable entity response
func (o *UpdateCubeSatVHFTransceiverUnprocessableEntity) WithPayload(payload *models.Error) *UpdateCubeSatVHFTransceiverUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat v h f transceiver unprocessable entity response
func (o *UpdateCubeSatVHFTransceiverUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatVHFTransceiverUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCubeSatVHFTransceiverInternalServerErrorCode is the HTTP code returned for type UpdateCubeSatVHFTransceiverInternalServerError
const UpdateCubeSatVHFTransceiverInternalServerErrorCode int = 500

/*
UpdateCubeSatVHFTransceiverInternalServerError Internal server error

swagger:response updateCubeSatVHFTransceiverInternalServerError
*/
type UpdateCubeSatVHFTransceiverInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCubeSatVHFTransceiverInternalServerError creates UpdateCubeSatVHFTransceiverInternalServerError with default headers values
func NewUpdateCubeSatVHFTransceiverInternalServerError() *UpdateCubeSatVHFTransceiverInternalServerError {

	return &UpdateCubeSatVHFTransceiverInternalServerError{}
}

// WithPayload adds the payload to the update cube sat v h f transceiver internal server error response
func (o *UpdateCubeSatVHFTransceiverInternalServerError) WithPayload(payload *models.Error) *UpdateCubeSatVHFTransceiverInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update cube sat v h f transceiver internal server error response
func (o *UpdateCubeSatVHFTransceiverInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCubeSatVHFTransceiverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
