// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	models "github.com/Maksim646/space_vpx_satellite/internal/api/definition"
)

// UpdateCubeSatSolarPanelSideByProjectHandlerFunc turns a function with the right signature into a update cube sat solar panel side by project handler
type UpdateCubeSatSolarPanelSideByProjectHandlerFunc func(UpdateCubeSatSolarPanelSideByProjectParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCubeSatSolarPanelSideByProjectHandlerFunc) Handle(params UpdateCubeSatSolarPanelSideByProjectParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateCubeSatSolarPanelSideByProjectHandler interface for that can handle valid update cube sat solar panel side by project params
type UpdateCubeSatSolarPanelSideByProjectHandler interface {
	Handle(UpdateCubeSatSolarPanelSideByProjectParams, *models.Principal) middleware.Responder
}

// NewUpdateCubeSatSolarPanelSideByProject creates a new http.Handler for the update cube sat solar panel side by project operation
func NewUpdateCubeSatSolarPanelSideByProject(ctx *middleware.Context, handler UpdateCubeSatSolarPanelSideByProjectHandler) *UpdateCubeSatSolarPanelSideByProject {
	return &UpdateCubeSatSolarPanelSideByProject{Context: ctx, Handler: handler}
}

/*
	UpdateCubeSatSolarPanelSideByProject swagger:route PUT /projects/{project_id}/solar_panel_side CubeSatProject updateCubeSatSolarPanelSideByProject

Update the Solar Panel Side of a CubeSat Project
*/
type UpdateCubeSatSolarPanelSideByProject struct {
	Context *middleware.Context
	Handler UpdateCubeSatSolarPanelSideByProjectHandler
}

func (o *UpdateCubeSatSolarPanelSideByProject) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateCubeSatSolarPanelSideByProjectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
