// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BoardComputingModuleList board computing module list
//
// swagger:model BoardComputingModuleList
type BoardComputingModuleList struct {

	// board computering modules
	BoardComputeringModules []*BoardComputingModule `json:"board_computering_modules"`

	// count
	// Required: true
	Count *int64 `json:"count"`
}

// Validate validates this board computing module list
func (m *BoardComputingModuleList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBoardComputeringModules(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BoardComputingModuleList) validateBoardComputeringModules(formats strfmt.Registry) error {
	if swag.IsZero(m.BoardComputeringModules) { // not required
		return nil
	}

	for i := 0; i < len(m.BoardComputeringModules); i++ {
		if swag.IsZero(m.BoardComputeringModules[i]) { // not required
			continue
		}

		if m.BoardComputeringModules[i] != nil {
			if err := m.BoardComputeringModules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("board_computering_modules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("board_computering_modules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BoardComputingModuleList) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this board computing module list based on the context it is used
func (m *BoardComputingModuleList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBoardComputeringModules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BoardComputingModuleList) contextValidateBoardComputeringModules(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BoardComputeringModules); i++ {

		if m.BoardComputeringModules[i] != nil {

			if swag.IsZero(m.BoardComputeringModules[i]) { // not required
				return nil
			}

			if err := m.BoardComputeringModules[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("board_computering_modules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("board_computering_modules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BoardComputingModuleList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BoardComputingModuleList) UnmarshalBinary(b []byte) error {
	var res BoardComputingModuleList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
