// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Chassises chassises
//
// swagger:model Chassises
type Chassises struct {

	// chassises
	Chassises []*Chassis `json:"chassises"`

	// count
	// Required: true
	Count *int64 `json:"count"`
}

// Validate validates this chassises
func (m *Chassises) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChassises(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Chassises) validateChassises(formats strfmt.Registry) error {
	if swag.IsZero(m.Chassises) { // not required
		return nil
	}

	for i := 0; i < len(m.Chassises); i++ {
		if swag.IsZero(m.Chassises[i]) { // not required
			continue
		}

		if m.Chassises[i] != nil {
			if err := m.Chassises[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chassises" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chassises" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Chassises) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this chassises based on the context it is used
func (m *Chassises) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChassises(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Chassises) contextValidateChassises(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Chassises); i++ {

		if m.Chassises[i] != nil {

			if swag.IsZero(m.Chassises[i]) { // not required
				return nil
			}

			if err := m.Chassises[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chassises" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chassises" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Chassises) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Chassises) UnmarshalBinary(b []byte) error {
	var res Chassises
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
