// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SolarPanel solar panel
//
// swagger:model SolarPanel
type SolarPanel struct {

	// Number of axes
	CoilArea float64 `json:"coil_area,omitempty"`

	// Shock response spectrum value
	CoilResistance int64 `json:"coil_resistance,omitempty"`

	// Timestamp of creation
	CreatedAt int64 `json:"created_at,omitempty"`

	// Minimum random vibration
	Efficiency int64 `json:"efficiency,omitempty"`

	// Size of the chassis
	Height float64 `json:"height,omitempty"`

	// Unique identifier for the chassis (auto-generated)
	// Required: true
	ID *int64 `json:"id"`

	// Maximum random vibration
	Imp float64 `json:"imp,omitempty"`

	// Minimum non-operating temperature in degrees Celsius
	Interface string `json:"interface,omitempty"`

	// Maximum sine vibration
	Isc float64 `json:"isc,omitempty"`

	// Name of the chassis
	Length float64 `json:"length,omitempty"`

	// Maximum operating temperature in degrees Celsius
	MaxOperatingTemperature float64 `json:"max_operating_temperature,omitempty"`

	// Peak overload spectrum value 2
	MechanicalShock int64 `json:"mechanical_shock,omitempty"`

	// Peak overload spectrum value 1
	MechanicalVibration int64 `json:"mechanical_vibration,omitempty"`

	// Minimum operating temperature in degrees Celsius
	MinOperatingTemperature float64 `json:"min_operating_temperature,omitempty"`

	// Timestamp of the last update
	UpdatedAt int64 `json:"updated_at,omitempty"`

	// Minimum sine vibration
	Vmp float64 `json:"vmp,omitempty"`

	// Overload capacity
	Voc float64 `json:"voc,omitempty"`

	// Maximum non-operating temperature in degrees Celsius
	Weight float64 `json:"weight,omitempty"`

	// Number of slots in the chassis
	Width float64 `json:"width,omitempty"`
}

// Validate validates this solar panel
func (m *SolarPanel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SolarPanel) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this solar panel based on context it is used
func (m *SolarPanel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SolarPanel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SolarPanel) UnmarshalBinary(b []byte) error {
	var res SolarPanel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
