name: Go Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run Go tests
      run: go test ./...

    - name: Setup docker-compose.yml from secret
      run: |
        mkdir -p space_vpx_satellite/space_vpx_satellite
        echo "$DOCKER_COMPOSE_YML" > space_vpx_satellite/space_vpx_satellite/docker-compose.yml
      env:
        DOCKER_COMPOSE_YML: ${{ secrets.DOCKER_COMPOSE_YML }}

    - name: Build Docker image
      run: make build

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/backend
          git pull
          docker compose down
          docker compose up -d --build
